import { TrpcProvider } from './../util/trpc/trpc-provider';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TrpcProvider>{children} </TrpcProvider>
      </body>
    </html>
  );
}
