import React from 'react';

import { Body } from '@smartcoorp/ui/body';
import { Headline } from '@smartcoorp/ui/headline';
import { space3XL } from '@smartcoorp/ui/tokens';

import { CodeBlock } from '../shared/code-block';
import { TableOfContent } from '../shared/table-of-contents';

import { codeSnippets, headings } from './helpers';
import { Container, DocumentationContainer } from './json-rendering.styles';

export const JSONRendering = async () => {
  return (
    <Container>
      <DocumentationContainer id="usage">
        <Headline size="xlarge" id="title" as="h1">
          JSON Rendering
        </Headline>
        <Body
          noMargin
          style={{
            marginBottom: space3XL,
          }}
        >
          Learn how to render SmartEditor content in JSON format.
        </Body>
        <section id="introduction">
          <Headline size="large" as="h2">
            Introduction
          </Headline>
          <Body noMargin>
            In this documentation, we will guide you through the process of
            rendering the content of the JSON data source extracted from
            SmartEditor in a React Application. JSON is a popular data format
            for exchanging information, and integrating it into a React
            application can be a common requirement. We will provide
            step-by-step instructions and examples to help you achieve this
            goal.
          </Body>
        </section>
        <section id="prerequisites">
          <Headline size="large" as="h2">
            Prerequisites
          </Headline>
          <Body noMargin>
            Before you begin, ensure you have the following prerequisites in
            place:
          </Body>

          <ul>
            <li>
              <Body lineHeight="increased">
                A react applicaton or library project.
              </Body>
            </li>

            <li>
              <Body lineHeight="increased">
                Basic knowledge of JavaScript and React.
              </Body>
            </li>

            <li>
              <Body lineHeight="increased">
                The JSON data source that you want to render.
              </Body>
            </li>
          </ul>
        </section>
        <section id="data-structure">
          <Headline size="large" as="h2">
            Data structure
          </Headline>
          <Body noMargin>
            The <code>JSON</code> structure is divided in two parts (keys):{' '}
            <code>blocks</code> and <code>chains</code>.
          </Body>
          <Body>
            Blocks contain the information related to each block in the post
            with <b>no specific order</b>. You can obtain the data of any block
            by accessing the object with that block&apos;s <code>id</code> .
            Each block contains the relevant information to be rendered: the
            identifier (<code>id</code>), the chain&apos;s id (the chain to
            which the block belongs, <code>chainId</code>), the type of the
            block (<code>type</code>) and the content of the block (styling,
            configurations, text, etc.)
          </Body>
          <Body>
            Chains contain the order of the blocks. Multiple chains can compose
            a post. However, each post will always have the <code>main</code>{' '}
            chain. New chains are part of the <code>Column</code> blocks. The id
            of the main chain is always the same. On the other hand, the ids of
            the chains generated by <code>Column</code> blocks have two parts
            divided by <code>-</code>. The first part corresponds to the{' '}
            <code>id</code> of the <code>Column</code> block that generates the
            chain and the second part is randomly generated.
          </Body>
        </section>
        <section>
          <section id="how-to-render-json">
            <Headline size="large" as="h2">
              How to render JSON
            </Headline>
            <Body>
              In this section, we will show you how to render the{' '}
              <code>JSON</code> data source. In order to render the{' '}
              <code>JSON</code> data source, we will need to create multiple
              React components:
            </Body>
          </section>
          <section id="blocks">
            <Headline size="medium" as="h3">
              Block components
            </Headline>
            <Body>
              A <code>Block</code> component is a React component that renders a
              block of content. It will receive the block data as props and
              render the content.
            </Body>
          </section>
          <section id="header">
            <Headline size="medium" noMargin as="h4">
              Header
            </Headline>
            <CodeBlock code={codeSnippets.headerBlock} />
          </section>

          <section id="paragraph">
            <Headline size="medium" noMargin as="h4">
              Paragraph
            </Headline>
            <CodeBlock code={codeSnippets.paragraphBlock} />
          </section>

          <section id="list">
            <Headline size="medium" noMargin as="h4">
              List
            </Headline>
            <CodeBlock code={codeSnippets.listBlock} />
          </section>

          <section id="image">
            <Headline size="medium" noMargin as="h4">
              Image
            </Headline>
            <CodeBlock code={codeSnippets.imageBlock} />
          </section>

          <section id="link">
            <Headline size="medium" noMargin as="h4">
              Link
            </Headline>
            <CodeBlock code={codeSnippets.linkBlock} />
          </section>

          <section id="columns">
            <Headline size="medium" noMargin as="h4">
              Columns
            </Headline>
            <CodeBlock code={codeSnippets.columnBlock} />
          </section>
          <section id="block-chain">
            <Headline size="medium" as="h3">
              BlockChain component
            </Headline>
            <Body>
              The <code>BlockChain</code> component is the one in charge of
              rendering the desired chain and all it&apos;s successors. It
              receives the blocks, chains and chainId as props and render the
              specific chain content using the Block components.
            </Body>
            <Body>
              The <code>BlockChain</code> component is a recursive component. It
              maps over all the block&apos;s ids in the chain and render them
              using the specific <code>Block</code> component. Whenever it finds
              a <code>Column</code> block it maps over all the chains of that{' '}
              <code>Column</code> block (the chains which are part of the
              blockk&apos;s content). Then, it renders again the{' '}
              <code>BlockChain</code> component with the id of the wanted chain.
            </Body>

            <CodeBlock code={codeSnippets.renderJSON} />
            <Body>
              In order to render all the post, you will need to render the{' '}
              <code>main</code> chain like this:
            </Body>
            <CodeBlock code={codeSnippets.mainChain} />
          </section>
        </section>
      </DocumentationContainer>

      <div
        style={{
          position: 'relative',
        }}
      >
        <TableOfContent headings={headings} />
      </div>
    </Container>
  );
};
