export const MODIFY_FIELD = 'MODIFY_FIELD';
export const MODIFY_LINK_DATA = 'MODIFY_LINK_DATA';
export const REMOVE_BLOCKS = 'REMOVE_BLOCKS';
export const ADD_BLOCKS = 'ADD_BLOCKS';
export const REPLACE_BLOCKS = 'REPLACE_BLOCKS';
export const SPLIT_TEXT_FIELD = 'SPLIT_TEXT_FIELD';
export const MERGE_TEXT_FIELDS = 'MERGE_TEXT_FIELDS';
export const REMOVE_LAST_LIST_ITEM = 'REMOVE_LAST_LIST_ITEM';
export const UNDO = 'UNDO';
export const REDO = 'REDO';
export const COPY_BLOCKS = 'COPY_BLOCKS';

export const undoableActions = [
  MODIFY_FIELD,
  REMOVE_BLOCKS,
  ADD_BLOCKS,
  REPLACE_BLOCKS,
  SPLIT_TEXT_FIELD,
  MERGE_TEXT_FIELDS,
  REMOVE_LAST_LIST_ITEM,
] as const;
